import { useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { InputField } from "../../components/ui/input-field";
import { validatePassword, validatePasswordConfirmation } from "../../lib/validation";
import { resetPassword } from "../../services/authService";
import { ApiError } from "../../services/api";
export default function ResetPassword() { const [params] = useSearchParams(); const token = params.get("token"); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [message,setMessage]=useState(""); const [sending,setSending]=useState(false); const submit=async(e:FormEvent)=>{e.preventDefault(); const error=validatePassword(password)||validatePasswordConfirmation(confirm,password); if(!token||error){setMessage(error??"El enlace para restablecer la contraseña no es válido o ya fue utilizado.");return;} setSending(true);try{setMessage((await resetPassword({token,password,passwordConfirm:confirm})).message);}catch(error){setMessage(error instanceof ApiError&&error.code==="EXPIRED_RESET_TOKEN"?"El enlace para restablecer la contraseña venció.":error instanceof ApiError&&error.code==="INVALID_RESET_TOKEN"?"El enlace para restablecer la contraseña no es válido o ya fue utilizado.":"No se pudo restablecer la contraseña. Intentá nuevamente.");}finally{setSending(false);}}; return <main className="min-h-screen grid place-items-center p-4"><Card className="w-full max-w-md"><CardHeader><CardTitle>Restablecer contraseña</CardTitle></CardHeader><CardContent>{message === "Tu contraseña fue restablecida correctamente." ? <Button asChild><Link to="/">Iniciar sesión</Link></Button> : <form className="space-y-4" onSubmit={submit}><InputField id="new-password" errorId="new-password-error" label="Nueva contraseña" type="password" value={password} onChange={(e)=>setPassword(e.target.value)} required/><InputField id="new-password-confirm" errorId="new-password-confirm-error" label="Repetir nueva contraseña" type="password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} required/>{message&&<p role="alert">{message}</p>}<Button disabled={sending}>{sending?"Enviando...":"Restablecer contraseña"}</Button></form>}</CardContent></Card></main>; }
