import { useEffect, useState } from "react";
import { adminService } from "../../services/adminService";
import type { AdminMetrics, AdminUser } from "../../types/admin";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";

const errorMessage = (error: unknown) => error instanceof Error ? error.message : "No se pudo completar la operación.";

export function AdminMetricsSection() { const [metrics, setMetrics] = useState<AdminMetrics>(); const [error, setError] = useState(""); useEffect(() => { void adminService.metrics().then(setMetrics).catch((reason) => setError(errorMessage(reason))); }, []); if (error) return <p role="alert">{error}</p>; if (!metrics) return <p role="status">Cargando métricas...</p>; return <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{[["Usuarios interesados", metrics.registeredUsers], ["Publicadores", metrics.publishers], ["Publicaciones activas", metrics.activeProperties], ["Publicaciones pausadas", metrics.pausedProperties], ["Visualizaciones", metrics.totalViews], ["Consultas", metrics.totalConsultations]].map(([label, value]) => <Card key={String(label)}><CardContent className="py-5"><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></CardContent></Card>)}</div>; }

export function AdminUsersSection() { const [users, setUsers] = useState<AdminUser[]>([]); const [editing, setEditing] = useState<AdminUser | null>(null); const [error, setError] = useState(""); useEffect(() => { void adminService.users({ page: "1", limit: "20" }).then((value) => setUsers(value.users)).catch((reason) => setError(errorMessage(reason))); }, []); const save = async () => { if (!editing) return; try { const user = await adminService.updateUser(editing.id, { firstName: editing.firstName, lastName: editing.lastName, phone: editing.phone }); setUsers((items) => items.map((item) => item.id === user.user.id ? user.user : item)); setEditing(null); } catch (reason) { setError(errorMessage(reason)); } }; return <section className="space-y-4">{error && <p role="alert">{error}</p>}<div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{users.map((user) => <tr key={user.id} className="border-t"><td className="p-2">{user.firstName} {user.lastName}<br/>{user.email}</td><td>{user.role}</td><td className="space-x-2"><Button variant="outline" onClick={() => setEditing(user)}>Editar</Button><Button variant="outline" onClick={() => void (user.accountStatus === "active" ? adminService.disableUser(user.id) : adminService.reactivateUser(user.id)).then((result) => setUsers((items) => items.map((item) => item.id === user.id ? result.user : item))).catch((reason) => setError(errorMessage(reason)))}>{user.accountStatus === "active" ? "Deshabilitar" : "Reactivar"}</Button></td></tr>)}</tbody></table></div>{editing && <div className="rounded-lg border p-4 space-y-3"><input className="w-full rounded border p-2" aria-label="Nombre" value={editing.firstName} onChange={(event) => setEditing({ ...editing, firstName: event.target.value })}/><input className="w-full rounded border p-2" aria-label="Apellido" value={editing.lastName} onChange={(event) => setEditing({ ...editing, lastName: event.target.value })}/><input className="w-full rounded border p-2" aria-label="Teléfono" value={editing.phone ?? ""} onChange={(event) => setEditing({ ...editing, phone: event.target.value || null })}/><Button onClick={() => void save()}>Guardar cambios</Button><Button variant="outline" onClick={() => setEditing(null)}>Cancelar</Button></div>}</section>; }
