import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import SearchBarAdmin, { type AdminPropertyFilters } from "../../components/SearchBarAdmin";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { OPERATION_TYPES, PUBLICATION_STATUSES } from "../../constants/property";
import { formatPrice } from "../../lib/formatters";
import { adminService } from "../../services/adminService";
import type { AdminProperty, AdminUser } from "../../types/admin";

const initialFilters: AdminPropertyFilters = { q: "", status: "all", operationType: "all" };
const statusClass = { active: "border-green-500 text-green-700 bg-white", paused: "border-amber-500 text-amber-700 bg-white", deleted: "border-destructive/50 text-destructive bg-white" };

export function AdminPropertiesSection() {
  const [properties, setProperties] = useState<AdminProperty[]>([]); const [publishers, setPublishers] = useState<AdminUser[]>([]); const [filters, setFilters] = useState(initialFilters); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await adminService.properties({ q: filters.q || undefined, status: filters.status, operationType: filters.operationType === "all" ? undefined : filters.operationType, page: "1", limit: "20" }); setProperties(response.properties); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudieron cargar las publicaciones."); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void adminService.users({ role: "publisher", status: "active", page: "1", limit: "100" }).then((result) => setPublishers(result.users)).catch(() => setPublishers([])); }, []);
  const publisherName = (id: string) => { const publisher = publishers.find((item) => item.id === id); return publisher ? `${publisher.firstName} ${publisher.lastName}` : "Publicador"; };
  return <section aria-labelledby="admin-properties-title"><SearchBarAdmin filters={filters} onChange={setFilters} /><div className="mb-6"><h2 id="admin-properties-title" className="text-2xl font-bold">Publicaciones</h2></div>{error ? <div className="space-y-3"><p role="alert">{error}</p><Button variant="outline" onClick={() => void load()}>Reintentar</Button></div> : <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[820px] text-left"><thead className="bg-muted"><tr><th className="p-3">Imagen</th><th className="p-3">Título</th><th className="p-3">Publicador</th><th className="p-3">Ubicación</th><th className="p-3">Categoría</th><th className="p-3">Estado</th><th className="p-3 text-right">Acciones</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-4" role="status">Cargando publicaciones...</td></tr> : properties.length === 0 ? <tr><td colSpan={7} className="p-4" role="status">No hay publicaciones que coincidan con la búsqueda.</td></tr> : properties.map((property) => <tr key={property.id} className="border-t hover:bg-muted/30"><td className="p-3">{property.images[0] ? <img src={property.images[0]} alt={property.title} className="h-16 w-16 rounded object-cover" /> : <div className="h-16 w-16 rounded bg-muted" />}</td><td className="p-3"><p className="font-medium">{property.title}</p><p className="text-sm text-muted-foreground">{formatPrice(Number(property.price), property.currency)}</p></td><td className="p-3">{publisherName(property.publisherId)}</td><td className="p-3">{property.city?.name ?? "Sin localidad"}{property.province?.name ? `, ${property.province.name}` : ""}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold text-white ${property.operationType === "rent" ? "bg-[#477ce0]" : property.operationType === "sale" ? "bg-[#58b5e0]" : "bg-accent"}`}>{OPERATION_TYPES[property.operationType]}</span></td><td className="p-3"><Badge className={`rounded-full ${statusClass[property.publicationStatus]}`}>{PUBLICATION_STATUSES[property.publicationStatus]}</Badge></td><td className="p-3 text-right"><Button asChild variant="outline" size="sm"><Link to={`/admin/properties/${property.id}`}>Ver Más</Link></Button></td></tr>)}</tbody></table></div>}{!loading && !error && <p className="mt-3 text-right text-sm text-muted-foreground">Se muestran hasta 20 publicaciones.</p>}</section>;
}
